/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package org.gradle.inverno

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class InvernoGradlePlugin implements Plugin<Project> {
    void apply(Project project) {
        project.apply(plugin: 'application')

        /**
         * Utilities:
         *      FindModuleReferences - iterate over runtime dependencies and extract ModuleReference objects for each
         *      (see https://github.com/inverno-io/inverno-tools/blob/f0f18c808ff285eab4fefdac774c7d2a5939a8bb/inverno-maven-plugin/src/main/java/io/inverno/tool/maven/internal/task/ResolveDependenciesTask.java#L110)
         *
         * Tasks:
         *      ModularizeDependenciesTask - iterate over the module references from FindModuleReferences and for each:
         *          - add Automatic-Module-Name to manifest
         *          - explode the jar file to a temp dir
         *          - generate the module-info file into the temp dir (using the jdeps command)
         *          (see https://github.com/inverno-io/inverno-tools/blob/f0f18c808ff285eab4fefdac774c7d2a5939a8bb/inverno-maven-plugin/src/main/java/io/inverno/tool/maven/internal/task/ModularizeDependenciesTask.java#L81)
         *
         *      CompileModuleDependenciesTask - iterate over the generated module info files and compile them
         *          - perhaps this could be a normal java compile task?
         *          (see https://github.com/inverno-io/inverno-tools/blob/f0f18c808ff285eab4fefdac774c7d2a5939a8bb/inverno-maven-plugin/src/main/java/io/inverno/tool/maven/internal/task/CompileModuleDescriptorsTask.java#L61)
         *
         *      RepackageDependenciesTask - iterate over the modularized dependencies and repackage the jars with the compile module info files
         *          (see https://github.com/inverno-io/inverno-tools/blob/f0f18c808ff285eab4fefdac774c7d2a5939a8bb/inverno-maven-plugin/src/main/java/io/inverno/tool/maven/internal/task/PackageModularizedDependenciesTask.java#L63)
         */
    }
}
